== Getting Started

[[requirements]]
=== Requirements
You need Java JRE installed (Java 8 or later).

You need http://kafka.apache.org[Apache Kafka] installed (0.10.1.0 or later). Kafka can be downloaded
from https://kafka.apache.org/downloads.html.

=== Quick Start
This quick start tutorial sets up a single node Zookeeper and Kafka and runs the sample reactive producer and
consumer. Instructions to set up multi-broker clusters are available http://kafka.apache.org/documentation#quickstart_multibroker[here].

==== Start Kafka

If you haven't yet downloaded Kafka, download Kafka version https://www.apache.org/dyn/closer.cgi?path=/kafka/0.10.1.0/kafka_2.11-0.10.1.0.tgz[0.10.1.0] or later.

Unzip the release and set KAFKA_DIR to the installation directory. For example,

[source]
--------
> tar xfzC kafka_2.11-0.10.1.0.tgz /opt
> export KAFKA_DIR=/opt/kafka_2.11-0.10.1.0
--------

Start a single-node Zookeeper instance using the Zookeeper installation included in the Kafka download:

[source]
--------
> $KAFKA_DIR/bin/zookeeper-server-start.sh $KAFKA_DIR/config/zookeeper.properties > /tmp/zookeeper.log &
--------

Start a single-node Kafka instance:

[source]
--------
> $KAFKA_DIR/bin/kafka-server-start.sh $KAFKA_DIR/config/server.properties > /tmp/kafka.log &
--------

Create a Kafka topic:

[source]
--------
> $KAFKA_DIR/bin/kafka-topics.sh --zookeeper localhost:2181 --create --replication-factor 1 --partitions 2 --topic demo-topic
Created topic "demo-topic".
--------

Check that Kafka topic was created successfully:

[source]
--------
> $KAFKA_DIR/bin/kafka-topics.sh --zookeeper localhost:2181 --describe
Topic:demo-topic	PartitionCount:2	ReplicationFactor:1	Configs:
	Topic: demo-topic	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
	Topic: demo-topic	Partition: 1	Leader: 0	Replicas: 0	Isr: 0
--------


==== Run Reactor Kafka Samples

Download and build Reactor Kafka from https://github.com/reactor/reactor-kafka/.

[source]
--------
> git clone https://github.com/reactor/reactor-kafka
> cd reactor-kafka
> ./gradlew jar
--------

Set `CLASSPATH` for running reactor-kafka samples. `CLASSPATH` can be obtained using the classpath task of the samples sub-project.

[source]
--------
> export CLASSPATH=`./gradlew -q :reactor-kafka-samples:classpath`
--------


===== Sample Producer

See https://github.com/reactor/reactor-kafka/blob/master/reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleProducer.java for sample producer code.

Run sample producer:

[source]
--------
> $KAFKA_DIR/bin/kafka-run-class.sh reactor.kafka.samples.SampleProducer
--------

The sample producer sends 20 messages to Kafka topic `demo-topic` using the default partitioner. The partition
and offset of each published message is output to console.

===== Sample Consumer

See https://github.com/reactor/reactor-kafka/blob/master/reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleConsumer.java for sample consumer code.

Run sample consumer:

[source]
--------
> $KAFKA_DIR/bin/kafka-run-class.sh reactor.kafka.samples.SampleConsumer
--------

The sample consumer consumes messages on topic `demo-topic` and prints the message on the console. The 20 messages
published by the Producer sample should appear on the console.

