language: java
jdk:
  - openjdk8

sudo: required
services:
  - docker

script: ./gradlew check -i

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
