[[motivation]]
= Motivation

[[motivation-functional]]
== Functional interface for Kafka

Reactor Kafka is a functional Java API for Kafka. For applications that are written in functional style,
this API enables Kafka interactions to be integrated easily without requiring non-functional
asynchronous produce or consume APIs to be incorporated into the application logic.


[[back-pressure]]
== Non-blocking Back-pressure

The Reactor Kafka API benefits from non-blocking back-pressure provided by Reactor. For example, in a pipeline, where
messages received from an external source (e.g. an HTTP proxy) are published to Kafka, back-pressure can be applied easily to the
whole pipeline, limiting the number of messages in-flight and controlling memory usage. Messages flow through
the pipeline as they are available, with Reactor taking care of limiting the flow rate to avoid overflow,
keeping application logic simple.

[[end-to-end-reactive]]
== End-to-end Reactive Pipeline

The value proposition for Reactor Kafka is the efficient utilization of resources in applications with multiple
external interactions where Kafka is one of the external systems. End-to-end reactive pipelines benefit from
non-blocking back-pressure and efficient use of threads, enabling a large number of concurrent requests to be
processed efficiently. The optimizations provided by Project Reactor enable development of reactive applications
with very low overheads and predictable capacity planning to deliver low-latency, high-throughput pipelines.

[[comparison]]
== Comparisons with other Kafka APIs

Reactor Kafka is not intended to replace any of the existing Kafka APIs. Instead, it is aimed at providing
an alternative API for reactive event-driven applications.

[[kafka-producer-and-consumer-apis]]
=== Kafka Producer and Consumer APIs

For non-reactive applications, Kafka's Producer/Consumer API provides a low latency interface to publish
messages to Kafka and consume messages from Kafka.

Applications using Kafka as a message bus using this API may consider switching to Reactor Kafka if
the application is implemented in a functional style.

[[kafka-connect-api]]
=== Kafka Connect API

https://kafka.apache.org/documentation#connect[Kafka Connect] provides a simple interface to migrate messages
from an external data system (e.g. a database) to one or more Kafka topics. Using existing connectors,
this migration can be performed without writing any new code.

Applications using the connector API may consider using Reactor Kafka if a reactive API is available for
the external data system and transformations are required for the data. When transformations involve
other I/O (e.g. to obtain additional information from another database), a reactive pipeline
benefits from end-to-end non-blocking back-pressure provided by Reactor. Messages from/to different Kafka
partitions can be processed in parallel, improving throughput by avoiding blocking for I/O.
The pull model in Reactor controls the pace of messages flowing through the pipeline, enabling efficient
use of threads and memory without the need for overflow handling in the application.

[[kafka-streams-api]]
=== Kafka Streams API

https://kafka.apache.org/documentation#streams[Kafka Streams] provides lightweight APIs to build stream processing
applications that process data stored in Kafka using standard streaming concepts and transformation primitives.
Using a simple threading model, the streams API avoids the need for back-pressure. This model works well in cases
where transformations do not involve external interactions.

Reactor Kafka is useful for streams applications which process data from Kafka and use external interactions
(e.g. get additional data for records from a database) for transformations. In this case, Reactor can provide end-to-end
non-blocking back-pressure combined with better utilization of resources if all external interactions use the reactive model.


